---
# tasks file for db_config
- name: Check if Postgres initialized
  stat:
    path: "{{ postgres_12_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state

- when: not r_postgres_init_dir_state.stat.exists
  name: Run Postgres initdb to initialize if postgres not initialized
  command: "{{ postgres_12_bin_path }}/postgresql-12-setup initdb"
  notify: restart_postgres
