---
# tasks file for db_config
- name: Disable built-module RHEL8 for postgresql
  ansible.builtin.shell:
    cmd: dnf -qy module disable postgresql

- name: add custom repository
  yum:
    name: "{{ postgres_rhel8_repo }}"
    state: present
    disable_gpg_check: true

- name: Install Postgres packages
  package:
    name: "{{ __package }}"
    state: present
  loop:
    - "{{ postgres_rhel8_repo }}"
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package
