---
- name: Create OpenStack Instances
  hosts: Control
 #connection: local
  gather_facts: false
  become: true 
  collections:
    - openstack.cloud
  roles:
    - osp_infra         #Deploy Openstack INFRA
    - cloud_inventory   #Create In-Memory-Inventory 
