---
- name: End to end smoke tests
  hosts: flask_servers:db_servers
  gather_facts: true
  become: true
  tags:
    - smoketest

  tasks:

    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ groups.db_servers[0] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.flask_servers[0] }}"
      run_once: true
      tags:
        - smoketest

