---
- name: Servers subscription, DNS and Firwall Configuration
  hosts: flask_servers, db_servers, lb_servers
  #become: false
  #become_user: root
  collections: 
    - openstack.cloud
  roles:
    - os_base

