---
- name: Test
  hosts: 192.168.50.231
  gather_facts: false
  collections:
    - openstack.cloud
  roles:
        - cloud_inventory   #Create In-Memory-Inventory 
    
- name: Servers subscription, DNS and Firwall Configuration
  hosts: flask_servers, db_servers, lb_servers
  become: true
  roles:
    - os_base

