---
# tasks file for flask_app
- name: "Install flask repo {{ flask_repo }}"
  git:
    repo: "{{ flask_repo }}"
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    update: yes
    force: yes
  tags:
    - git

- name: "Change flask repo owner to {{ flask_user }} recursively"
  file:
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    owner: "{{ flask_user }}"

