---
# tasks file for cloud_inventory
#
- name: Collection instance info
  os_server_info:
    cloud: "{{ guid }}-project"
  register: instances

- name: Build In-Memory inventory
  add_host:
    host: "{{ instance.name }}.{{ internal_domain }}"
    group: "{{ instance.metadata.AnsibleGroup }}"
    ansible_host: "{{ instance.private_v4 }}"
    ssh_private_key_file: "{{ home }}/.ssh/{{ guid }}key.pem"
  #when: instance.metadata.AnsibleGroup == "osp_instances"
  when: instance.metadata.AnsibleGroup == "{{ instance.metadata.AnsibleGroup }}"
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance
