---
# tasks file for osp_infra
- name: Create Instance
  #openstack.cloud.server:
  os_server:
    cloud: "{{ guid }}-project"
    name: "{{ instance.name }}"
    image: "{{ instance.image }}"
    key_name: "{{ instance.keypair }}"
    flavor: "{{ instance.flavor }}"
    security_groups: "{{ instance.security_group }}"
    delete_fip: yes
    wait: no
    nics:
    - net-name: "{{ instance.internal_network }}"
    meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name={{instance.metadata.deployment_name}}"
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
    
- name: Pause for 3 minutes to wait OSP full deployment
  pause:
    minutes: 3
